/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Lohitha Atluri
 */
public class FeedbackPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackPanel
     */
    public FeedbackPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffbuttonGroup = new javax.swing.ButtonGroup();
        servicesbuttonGroup = new javax.swing.ButtonGroup();
        visitbuttonGroup = new javax.swing.ButtonGroup();
        collectionbuttonGroup = new javax.swing.ButtonGroup();
        feedbackPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        staffLabel = new javax.swing.JLabel();
        staffRadioButton1 = new javax.swing.JRadioButton();
        staffRadioButton2 = new javax.swing.JRadioButton();
        staffRadioButton3 = new javax.swing.JRadioButton();
        staffRadioButton4 = new javax.swing.JRadioButton();
        staffRadioButton5 = new javax.swing.JRadioButton();
        servicesLabel = new javax.swing.JLabel();
        servicesRadioButton1 = new javax.swing.JRadioButton();
        servicesRadioButton2 = new javax.swing.JRadioButton();
        servicesRadioButton3 = new javax.swing.JRadioButton();
        servicesRadioButton4 = new javax.swing.JRadioButton();
        servicesRadioButton5 = new javax.swing.JRadioButton();
        visitLabel = new javax.swing.JLabel();
        visitRadioButton1 = new javax.swing.JRadioButton();
        visitRadioButton2 = new javax.swing.JRadioButton();
        visitRadioButton3 = new javax.swing.JRadioButton();
        visitRadioButton4 = new javax.swing.JRadioButton();
        collectionLabel = new javax.swing.JLabel();
        collectionRadioButton1 = new javax.swing.JRadioButton();
        collectionRadioButton2 = new javax.swing.JRadioButton();
        collectionRadioButton3 = new javax.swing.JRadioButton();
        collectionRadioButton4 = new javax.swing.JRadioButton();
        collectionRadioButton5 = new javax.swing.JRadioButton();
        suggestionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        suggestionTextArea = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();

        headingLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Feedback Form");

        nameLabel.setText("Name:");

        emailLabel.setText("Email:");

        staffLabel.setText("Staff:");

        staffbuttonGroup.add(staffRadioButton1);
        staffRadioButton1.setText("1");

        staffbuttonGroup.add(staffRadioButton2);
        staffRadioButton2.setText("2");

        staffbuttonGroup.add(staffRadioButton3);
        staffRadioButton3.setText("3");

        staffbuttonGroup.add(staffRadioButton4);
        staffRadioButton4.setText("4");

        staffbuttonGroup.add(staffRadioButton5);
        staffRadioButton5.setText("5");

        servicesLabel.setText("Services:");

        servicesbuttonGroup.add(servicesRadioButton1);
        servicesRadioButton1.setText("1");

        servicesbuttonGroup.add(servicesRadioButton2);
        servicesRadioButton2.setText("2");

        servicesbuttonGroup.add(servicesRadioButton3);
        servicesRadioButton3.setText("3");

        servicesbuttonGroup.add(servicesRadioButton4);
        servicesRadioButton4.setText("4");

        servicesbuttonGroup.add(servicesRadioButton5);
        servicesRadioButton5.setText("5");

        visitLabel.setText("Frequency of Visit:");

        visitbuttonGroup.add(visitRadioButton1);
        visitRadioButton1.setText("Daily");

        visitbuttonGroup.add(visitRadioButton2);
        visitRadioButton2.setText("Weekly");

        visitbuttonGroup.add(visitRadioButton3);
        visitRadioButton3.setText("Monthly");

        visitbuttonGroup.add(visitRadioButton4);
        visitRadioButton4.setText("Often");

        collectionLabel.setText("Collections:");

        collectionbuttonGroup.add(collectionRadioButton1);
        collectionRadioButton1.setText("1");

        collectionbuttonGroup.add(collectionRadioButton2);
        collectionRadioButton2.setText("2");

        collectionbuttonGroup.add(collectionRadioButton3);
        collectionRadioButton3.setText("3");

        collectionbuttonGroup.add(collectionRadioButton4);
        collectionRadioButton4.setText("4");

        collectionbuttonGroup.add(collectionRadioButton5);
        collectionRadioButton5.setText("5");

        suggestionLabel.setText("Suggestions:");

        suggestionTextArea.setColumns(20);
        suggestionTextArea.setRows(5);
        jScrollPane1.setViewportView(suggestionTextArea);

        submitButton.setText("Submit");

        javax.swing.GroupLayout feedbackPanelLayout = new javax.swing.GroupLayout(feedbackPanel);
        feedbackPanel.setLayout(feedbackPanelLayout);
        feedbackPanelLayout.setHorizontalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(emailLabel)
                        .addComponent(nameLabel))
                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffLabel)
                            .addComponent(visitLabel)
                            .addComponent(servicesLabel)
                            .addComponent(collectionLabel)
                            .addComponent(suggestionLabel))))
                .addGap(47, 47, 47)
                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(feedbackPanelLayout.createSequentialGroup()
                                .addComponent(visitRadioButton1)
                                .addGap(35, 35, 35)
                                .addComponent(visitRadioButton2))
                            .addGroup(feedbackPanelLayout.createSequentialGroup()
                                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                                        .addComponent(servicesRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(servicesRadioButton2))
                                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                                        .addComponent(staffRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(staffRadioButton2))
                                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                                        .addComponent(collectionRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(collectionRadioButton2)))
                                .addGap(39, 39, 39)
                                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(staffRadioButton3)
                                    .addComponent(servicesRadioButton3)
                                    .addComponent(collectionRadioButton3))))
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(feedbackPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(servicesRadioButton4)
                                    .addComponent(collectionRadioButton4))
                                .addGap(38, 38, 38)
                                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(collectionRadioButton5)
                                    .addComponent(servicesRadioButton5)
                                    .addComponent(staffRadioButton5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(feedbackPanelLayout.createSequentialGroup()
                                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(staffRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(visitRadioButton3)
                                        .addGap(18, 18, 18)))
                                .addComponent(visitRadioButton4)
                                .addGap(104, 104, Short.MAX_VALUE))))
                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 188, Short.MAX_VALUE))
                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(291, 291, 291))))
        );
        feedbackPanelLayout.setVerticalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackPanelLayout.createSequentialGroup()
                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(headingLabel)
                        .addGap(26, 26, 26)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel))
                        .addGap(18, 18, 18)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(visitLabel)
                            .addComponent(visitRadioButton1)
                            .addComponent(visitRadioButton2)
                            .addComponent(visitRadioButton3)
                            .addComponent(visitRadioButton4))
                        .addGap(31, 31, 31)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffLabel)
                            .addComponent(staffRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(servicesLabel)
                            .addComponent(servicesRadioButton1)
                            .addComponent(servicesRadioButton2)
                            .addComponent(servicesRadioButton3)
                            .addComponent(servicesRadioButton4))
                        .addGap(25, 25, 25)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(collectionLabel)
                            .addComponent(collectionRadioButton1)
                            .addComponent(collectionRadioButton2)
                            .addComponent(collectionRadioButton3)
                            .addComponent(collectionRadioButton4)
                            .addComponent(collectionRadioButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(staffRadioButton2)
                                    .addComponent(staffRadioButton3)
                                    .addComponent(staffRadioButton4)
                                    .addComponent(staffRadioButton5))
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                                .addComponent(servicesRadioButton5)
                                .addGap(48, 48, 48)))))
                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(suggestionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addComponent(submitButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feedbackPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel collectionLabel;
    private javax.swing.JRadioButton collectionRadioButton1;
    private javax.swing.JRadioButton collectionRadioButton2;
    private javax.swing.JRadioButton collectionRadioButton3;
    private javax.swing.JRadioButton collectionRadioButton4;
    private javax.swing.JRadioButton collectionRadioButton5;
    private javax.swing.ButtonGroup collectionbuttonGroup;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel servicesLabel;
    private javax.swing.JRadioButton servicesRadioButton1;
    private javax.swing.JRadioButton servicesRadioButton2;
    private javax.swing.JRadioButton servicesRadioButton3;
    private javax.swing.JRadioButton servicesRadioButton4;
    private javax.swing.JRadioButton servicesRadioButton5;
    private javax.swing.ButtonGroup servicesbuttonGroup;
    private javax.swing.JLabel staffLabel;
    private javax.swing.JRadioButton staffRadioButton1;
    private javax.swing.JRadioButton staffRadioButton2;
    private javax.swing.JRadioButton staffRadioButton3;
    private javax.swing.JRadioButton staffRadioButton4;
    private javax.swing.JRadioButton staffRadioButton5;
    private javax.swing.ButtonGroup staffbuttonGroup;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel suggestionLabel;
    private javax.swing.JTextArea suggestionTextArea;
    private javax.swing.JLabel visitLabel;
    private javax.swing.JRadioButton visitRadioButton1;
    private javax.swing.JRadioButton visitRadioButton2;
    private javax.swing.JRadioButton visitRadioButton3;
    private javax.swing.JRadioButton visitRadioButton4;
    private javax.swing.ButtonGroup visitbuttonGroup;
    // End of variables declaration//GEN-END:variables
}
