/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import Model.User;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import Model.UserMessage;
import Util.UserMessageDBConnector;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
/**
 *
 * @author Lohitha Atluri
 */
public class QueryPanel extends javax.swing.JPanel {

    private User userDetails = null;
    /**
     * Creates new form QueryPanel
     */
    private JPanel loginPanel;
    public QueryPanel(User user, JPanel loginPanel) {
        this.loginPanel = loginPanel;
        initComponents();
        userDetails = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commentTypeButtonGroup = new javax.swing.ButtonGroup();
        queryPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        complaintRadioButton = new javax.swing.JRadioButton();
        queryRadioButton = new javax.swing.JRadioButton();
        queryaboutLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryTextArea = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        feedbackRadioButton = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 500));

        queryPanel.setBackground(new java.awt.Color(204, 255, 204));

        headingLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Query Form");
        headingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        commentLabel.setText("Comment Type:");

        commentTypeButtonGroup.add(complaintRadioButton);
        complaintRadioButton.setText("Report");
        complaintRadioButton.setActionCommand("REPORT");
        complaintRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintRadioButtonActionPerformed(evt);
            }
        });

        commentTypeButtonGroup.add(queryRadioButton);
        queryRadioButton.setText("Query");
        queryRadioButton.setActionCommand("QUERY");
        queryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryRadioButtonActionPerformed(evt);
            }
        });

        queryaboutLabel.setText("Comment:");

        queryTextArea.setColumns(20);
        queryTextArea.setRows(5);
        jScrollPane1.setViewportView(queryTextArea);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        commentTypeButtonGroup.add(feedbackRadioButton);
        feedbackRadioButton.setText("Feedback");
        feedbackRadioButton.setActionCommand("FEEDBACK");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout queryPanelLayout = new javax.swing.GroupLayout(queryPanel);
        queryPanel.setLayout(queryPanelLayout);
        queryPanelLayout.setHorizontalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(queryPanelLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(submitButton)
                        .addGap(75, 75, 75)
                        .addComponent(clearButton))
                    .addGroup(queryPanelLayout.createSequentialGroup()
                        .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(queryPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(commentLabel)
                                    .addComponent(queryaboutLabel)))
                            .addGroup(queryPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(queryPanelLayout.createSequentialGroup()
                                .addComponent(complaintRadioButton)
                                .addGap(66, 66, 66)
                                .addComponent(queryRadioButton)
                                .addGap(38, 38, 38)
                                .addComponent(feedbackRadioButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        queryPanelLayout.setVerticalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentLabel)
                    .addComponent(complaintRadioButton)
                    .addComponent(queryRadioButton)
                    .addComponent(feedbackRadioButton))
                .addGap(18, 18, 18)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queryaboutLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(clearButton))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(queryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(queryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        UserMessage newMessage = new UserMessage();

        try {
            newMessage.setEmail(userDetails.getEmail());
            newMessage.setMessage(queryTextArea.getText());
            switch(commentTypeButtonGroup.getSelection().getActionCommand())
            {
                case "QUERY": 
                    newMessage.setType("Query");
                    break;
                case "REPORT":
                    newMessage.setType("Report");
                    newMessage.setEmail("");
                    break;
                case "FEEDBACK":
                    newMessage.setType("Feedback");
                    newMessage.setEmail("");
                    break;
                default:
                    newMessage.setType("Query");
                    break;
            }
            System.out.println("userDetails.getEmail()");
            System.out.println(userDetails.getEmail());
            System.out.println("queryTextArea.getText()");
            System.out.println(queryTextArea.getText());
            System.out.println("commentonbuttonGroup.getSelection().getActionCommand()");
            System.out.println(commentTypeButtonGroup.getSelection().getActionCommand());

            // Validate inputs
            if (newMessage.getMessage().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Comment is Mandatory");
                return;
            }

            if (newMessage.getType() == null || newMessage.getType().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Comment Type is Mandatory");
                return;
            }

            UserMessageDBConnector.addUserMessage(newMessage);

            JOptionPane.showMessageDialog(null, "Query sent Successfully", "Successful Message", JOptionPane.PLAIN_MESSAGE);
            cleanup();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error submitting query: " + e.getMessage());
        }
    
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        cleanup();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void queryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryRadioButtonActionPerformed

    }//GEN-LAST:event_queryRadioButtonActionPerformed

    private void complaintRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complaintRadioButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.setContentPane(new Homepage(userDetails, loginPanel));
        topFrame.invalidate();
        topFrame.validate();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel commentLabel;
    private javax.swing.ButtonGroup commentTypeButtonGroup;
    private javax.swing.JRadioButton complaintRadioButton;
    private javax.swing.JRadioButton feedbackRadioButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel queryPanel;
    private javax.swing.JRadioButton queryRadioButton;
    private javax.swing.JTextArea queryTextArea;
    private javax.swing.JLabel queryaboutLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
    public void cleanup()
    {
       commentTypeButtonGroup.clearSelection();
       queryTextArea.setText(null);
    }
}
